name: si_paling_undip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  go_router: ^14.2.8
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  provider: ^6.1.2
  google_sign_in_dartio: ^0.3.0
  firebase_admin: ^0.3.0
  syncfusion_flutter_calendar: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/image/universitas-diponegoro-logo.png
